### PR TITLE
Bugce

### PR DESCRIPTION
**Pull request by bugcebayindir**

### CODE REVIEW

**Comment by bugcebayindir** [comment]
added link for Docker Windows

**Review by shaq31415926 — CHANGES_REQUESTED** [review]
Could you please add more detailed instructions about downloading linux and how you all set up docker desktop in windows?

**Comment by bugcebayindir** [comment]
Installation links for Docker Window and manuel installation steps for older versions of WSL are added.

**Review by shaq31415926 — APPROVED** [review]
This is great, thanks very much

**Comment by shaq31415926** [comment]
This is great, thanks very much

**Pull request merged**
